---
name: base
channels:
  - conda-forge
  - defaults
  - anaconda
dependencies:
  - bzip2=1.0.8
  - ca-certificates
  - libexpat=2.5.0
  - libffi=3.4.2
  - libsqlite=3.44.0
  - libzlib=1.2.13
  - ncurses=6.4
  - openssl=3.1.4
  - readline=8.2
  - setuptools=68.2.2
  - tk=8.6.13
  - tzdata=2023c
  - wheel=0.41.3
  - xz=5.2.6
